name: reff_shared
description: A new Flutter package.
version: 0.0.1
author:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.12.0
  cloud_firestore: ^0.14.0+2
  timezone: ^0.5.7
  logging: ^0.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.1
  json_serializable: ^3.5.0
  freezed: ^0.12.1
  cloud_firestore_mocks: ^0.5.0+1
  effective_dart: ^1.2.4


flutter:
  uses-material-design: true